create or replace function public.get_company_id_by_code(p_company_code text) returns uuid language sql security definer set search_path=public stable as $$ select id from public.companies where company_code=p_company_code; $$;
revoke all on function public.get_company_id_by_code(text) from public;
grant execute on function public.get_company_id_by_code(text) to anon, authenticated;

create or replace function public.complete_instant_quest(p_quest_id uuid) returns table (success boolean, points_awarded integer, message text) language plpgsql security definer set search_path=public as $$ declare v_user_id uuid:=auth.uid(); v_company_id uuid; v_quest public.quests; v_completion_id uuid; begin if v_user_id is null then raise exception 'ログインが必要です'; end if; select company_id into v_company_id from public.profiles where id=v_user_id; if v_company_id is null then return query select false,0,'社員情報が見つかりません'; return; end if; select * into v_quest from public.quests where id=p_quest_id for update; if v_quest.id is null then return query select false,0,'クエストが見つかりません'; return; end if; if v_quest.status<>'published' or now()<v_quest.scheduled_at or now()>=v_quest.expires_at then return query select false,0,'このクエストは現在受け付けていません'; return; end if; insert into public.quest_completions (quest_id,user_id,company_id) values (p_quest_id,v_user_id,v_company_id) on conflict (quest_id,user_id) do nothing returning id into v_completion_id; if v_completion_id is null then return query select false,0,'このクエストは既に完了しています'; return; end if; insert into public.points_ledger (user_id,company_id,reason_type,quest_id,points) values (v_user_id,v_company_id,'instant_quest',p_quest_id,v_quest.points); return query select true,v_quest.points,'完了しました'; end; $$;
revoke all on function public.complete_instant_quest(uuid) from public, anon;
grant execute on function public.complete_instant_quest(uuid) to authenticated;

create or replace function public.complete_daily_quest(p_daily_quest_id uuid) returns table (success boolean, points_awarded integer, message text) language plpgsql security definer set search_path=public as $$ declare v_user_id uuid:=auth.uid(); v_company_id uuid; v_daily_quest public.daily_quests; v_today date; v_completion_id uuid; begin if v_user_id is null then raise exception 'ログインが必要です'; end if; select company_id into v_company_id from public.profiles where id=v_user_id; if v_company_id is null then return query select false,0,'社員情報が見つかりません'; return; end if; select * into v_daily_quest from public.daily_quests where id=p_daily_quest_id; if v_daily_quest.id is null or v_daily_quest.is_active=false then return query select false,0,'クエストが見つかりません'; return; end if; v_today:=(now() at time zone 'Asia/Tokyo')::date; insert into public.daily_quest_completions (daily_quest_id,user_id,company_id,completed_date) values (p_daily_quest_id,v_user_id,v_company_id,v_today) on conflict (daily_quest_id,user_id,completed_date) do nothing returning id into v_completion_id; if v_completion_id is null then return query select false,0,'本日はすでに完了しています'; return; end if; insert into public.points_ledger (user_id,company_id,reason_type,daily_quest_id,points) values (v_user_id,v_company_id,'daily_quest',p_daily_quest_id,v_daily_quest.points); return query select true,v_daily_quest.points,'完了しました'; end; $$;
revoke all on function public.complete_daily_quest(uuid) from public, anon;
grant execute on function public.complete_daily_quest(uuid) to authenticated;

create or replace function public.get_weekly_ranking() returns table (rank bigint, nickname text, total_points bigint, is_current_user boolean) language plpgsql security definer set search_path=public stable as $$ declare v_user_id uuid:=auth.uid(); v_company_id uuid; v_week_start date; begin if v_user_id is null then raise exception 'ログインが必要です'; end if; select company_id into v_company_id from public.profiles where id=v_user_id; if v_company_id is null then return; end if; v_week_start:=date_trunc('week',(now() at time zone 'Asia/Tokyo'))::date; return query with totals as (select p.id,p.nickname,p.ranking_opt_in,coalesce(sum(pl.points),0) as total_points from public.profiles p left join public.points_ledger pl on pl.user_id=p.id and pl.is_reversed=false and (pl.created_at at time zone 'Asia/Tokyo')::date between v_week_start and v_week_start+6 where p.company_id=v_company_id and (p.ranking_opt_in=true or p.id=v_user_id) group by p.id,p.nickname,p.ranking_opt_in) select rank() over (order by t.total_points desc) as rank,t.nickname,t.total_points,(t.id=v_user_id) as is_current_user from totals t order by t.total_points desc,t.nickname asc; end; $$;
revoke all on function public.get_weekly_ranking() from public, anon;
grant execute on function public.get_weekly_ranking() to authenticated;
