alter table public.companies enable row level security;
create policy "companies_select_own_or_admin" on public.companies for select to authenticated using (id=public.current_company_id() or public.is_super_admin());
create policy "companies_insert_admin_only" on public.companies for insert to authenticated with check (public.is_super_admin());
alter table public.profiles enable row level security;
create policy "profiles_select_self_or_company_or_admin" on public.profiles for select to authenticated using (id=auth.uid() or company_id=public.current_company_id() or public.is_super_admin());
create policy "profiles_update_self" on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());
alter table public.quests enable row level security;
create policy "quests_select_active_or_completed_or_admin" on public.quests for select to authenticated using (public.is_super_admin() or (status='published' and now()>=scheduled_at and now()<expires_at) or exists (select 1 from public.quest_completions qc where qc.quest_id=quests.id and qc.user_id=auth.uid()));
create policy "quests_insert_admin_only" on public.quests for insert to authenticated with check (public.is_super_admin());
create policy "quests_update_admin_only" on public.quests for update to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy "quests_delete_admin_only" on public.quests for delete to authenticated using (public.is_super_admin());
alter table public.daily_quests enable row level security;
create policy "daily_quests_select_active_or_admin" on public.daily_quests for select to authenticated using (is_active=true or public.is_super_admin());
alter table public.quest_completions enable row level security;
create policy "quest_completions_select_self" on public.quest_completions for select to authenticated using (user_id=auth.uid());
alter table public.daily_quest_completions enable row level security;
create policy "daily_quest_completions_select_self" on public.daily_quest_completions for select to authenticated using (user_id=auth.uid());
alter table public.points_ledger enable row level security;
create policy "points_ledger_select_self" on public.points_ledger for select to authenticated using (user_id=auth.uid());
alter table public.push_subscriptions enable row level security;
create policy "push_subscriptions_self" on public.push_subscriptions for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
alter table public.notification_deliveries enable row level security;
